[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.4"
  export = ["admin_api"]
  name = "admin_api"
  org = "elixir"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.27"